name: swift
version: '4.1'
summary: The Swift Programming Language
description: |
  Swift is a high-performance system programming language. It has a clean and
  modern syntax, offers seamless access to existing C and Objective-C code and
  frameworks, and is memory safe by default.

# TODO:
#  - Build from source http://paste.ubuntu.com/25564789/

confinement: strict
grade: devel
architectures: [ amd64 ]

parts:
  swift:
    plugin: make
    source: https://github.com/apple/swift
    build-packages:

      - git 
      - cmake 
      - ninja-build 
      - clang 
      - python 
      - uuid-dev 
      - libicu-dev 
      - icu-devtools 
      - libbsd-dev 
      - libedit-dev 
      - libxml2-dev 
      - libsqlite3-dev 
      - swig libpython-dev 
      - libncurses5-dev 
      - pkg-config 
      - libblocksruntime-dev 
      - libcurl4-openssl-dev 
      - autoconf 
      - libtool 
      - systemtap-sdt-dev 
      - tzdata 
      - rsync

apps:
  lldb:
    command: bin/lldb
  lldb-argdumper:
    command: bin/lldb-argdumper
  lldb-mi:
    command: bin/lldb-mi
  lldb-server:
    command: bin/lldb-server
  repl-swift:
    command: bin/repl_swift
  swift:
    command: bin/swift
  swift-autolink-extract:
    command: bin/swift-autolink-extract
  swift-build:
    command: bin/swift-build
  swift-build-tool:
    command: bin/swift-build-tool
  swift-demangle:
    command: bin/swift-demangle
  swift-package:
    command: bin/swift-package
  swift-test:
    command: bin/swift-test
  swiftc:
    command: bin/swiftc
  swift-run:
    command: bin/swift-run
  swift-format:
    command: bin/swift-format

