name: swift
version: '4.1'
summary: The Swift Programming Language
description: |
  Swift is a high-performance system programming language. It has a clean and
  modern syntax, offers seamless access to existing C and Objective-C code and
  frameworks, and is memory safe by default.

# TODO:
#  - Build from source http://paste.ubuntu.com/25564789/

confinement: strict
grade: devel
architectures: [ amd64 ]

parts:
  swift:
    plugin: dump
    source: https://swift.org/builds/swift-4.1-release/ubuntu1604/swift-4.1-RELEASE/swift-4.1-RELEASE-ubuntu16.04.tar.gz
    stage-packages:
      - clang
      - libblocksruntime0
      - libbsd0
      - libedit2
      - libicu-dev          # Yes, the -dev package is deliberately staged.
      - libncursesw5
      - libpython2.7
      - libsqlite3-0
      - libuutil1linux
      - libxml2
      - python2.7
      - libcurl4
      
apps:
  lldb:
    command: bin/lldb
  lldb-argdumper:
    command: bin/lldb-argdumper
  lldb-mi:
    command: bin/lldb-mi
  lldb-server:
    command: bin/lldb-server
  repl-swift:
    command: bin/repl_swift
  swift:
    command: bin/swift
  swift-autolink-extract:
    command: bin/swift-autolink-extract
  swift-build:
    command: bin/swift-build
  swift-build-tool:
    command: bin/swift-build-tool
  swift-demangle:
    command: bin/swift-demangle
  swift-package:
    command: bin/swift-package
  swift-test:
    command: bin/swift-test
  swiftc:
    command: bin/swiftc
  swift-run:
    command: bin/swift-run
  swift-format:
    command: bin/swift-format
