name: swift
version: '4.1'
summary: The Swift Programming Language
description: |
  Swift is a high-performance system programming language. It has a clean and
  modern syntax, offers seamless access to existing C and Objective-C code and
  frameworks, and is memory safe by default.

# TODO:
#  - Build from source http://paste.ubuntu.com/25564789/

confinement: strict
grade: devel
architectures: [ amd64 ]

parts:
  swift:
    plugin: dump
    source: https://swift.org/builds/swift-4.1-release/ubuntu1604/swift-4.1-RELEASE/swift-4.1-RELEASE-ubuntu16.04.tar.gz
    stage-packages:
      - clang
      - libblocksruntime0
      - libbsd0
      - libedit2
      - libicu-dev          # Yes, the -dev package is deliberately staged.
      - libncursesw5
      - libpython2.7
      - libsqlite3-0
      - libuutil1linux
      - libxml2
      - python2.7
      
apps:
  lldb:
    command: bin/lldb
    aliases: [ lldb ]
  lldb-4-0-0:
    command: bin/lldb-4.0.0
    aliases: [ lldb-4.0.0 ]
  lldb-argdumper:
    command: bin/lldb-argdumper
    aliases: [ lldb-argdumper ]
  lldb-mi:
    command: bin/lldb-mi
    aliases: [ lldb-mi ]

  lldb-server:
    command: bin/lldb-server
    aliases: [ lldb-server ]
  lldb-server-4-0-0:
    command: bin/lldb-server-4.0.0
    aliases: [ lldb-server-4.0.0 ]
  repl-swift:
    command: bin/repl_swift
    aliases: [ repl_swift ]
  swift:
    command: bin/swift
  swift-autolink-extract:
    command: bin/swift-autolink-extract
    aliases: [ swift-autolink-extract ]
  swift-build:
    command: bin/swift-build
    aliases: [ swift-build ]
  swift-build-tool:
    command: bin/swift-build-tool
    aliases: [ swift-build-tool ]
  swift-demangle:
    command: bin/swift-demangle
    aliases: [ swift-demangle ]
  swift-package:
    command: bin/swift-package
    aliases: [ swift-package ]
  swift-test:
    command: bin/swift-test
    aliases: [ swift-test ]
  swiftc:
    command: bin/swiftc
    aliases: [ swiftc ]
